'use client'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../../../public/css/style.css'
import '../../../public/css/responsive.css'
import '../../../public/css/bootstrap.min.css'
// import '../../public/css/custom.css'
import '../../../public/css/new.css'
import { useEffect } from 'react'

import { Providers } from '../../../store/providers'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function CheckOut({
  children,
}: {
  children: React.ReactNode
}) {  

  return (
    <html lang="en">
     <head>
     </head>
      <body className={inter.className}>
      <Providers>  
        {children}      
      </Providers>
      </body>
      
    </html>
  )
}
